web:
  replicaCount: 50
  image:
    repository: localhost:5000/lab-catalogo
    tag: "v2"
  service:
    type: NodePort
    nodePort: 30000

db:
  replicaCount: 1
  image:
    repository: localhost:5000/postgres
    tag: alpine3.14
  service:
    type: ClusterIP
  user_name: postgres
  password: 123@Mudar
  db_name: lab.catalogo  
  port: 5432 