apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-postgres
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
  type: {{ .Values.db.service.type }}
