apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-catalogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-catalogo
  template:
    metadata:
      labels:
        app: web-catalogo
    spec:
      containers:
      - name: web-catalogo
        image: localhost:5000/lab-catalogo:v3
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT 
            value: Development
          - name: ConnectionStrings__DefaultConnection
            value: "User ID=postgres;Password=123@Mudar;Server=postgresql-service-name;Port=5432;Database=lab.catalogo; Integrated Security=true;Pooling=true;"
          - name: "RabbitConfig__ConnectionString"            
            value: "amqps://flzouboh:aXbkPW9z8sy-hsqxexCMMKZ0flU0vTth@snake.rmq2.cloudamqp.com/flzouboh"                      
          - name: "RabbitConfig__QueueName"
            value: "catalogo-logs"
          - name: "RabbitConfig__ExchangeName"
            value: "logger"
          - name: "RabbitConfig__ExchangeType"
            value: "fanout"
          - name: "RabbitConfig__Routingkey"
            value: ""
          - name: "RedisConfig__InstanceName"
            value: "lab-catalogo"
          - name: "RedisConfig__Configuration"
            value: "redis-service-name:6379"
          - name: "RedisConfig__AbsoluteExpirationRelativeToNowFromSeconds"
            value: "3600"
          - name: "RedisConfig__SlidingExpirationFromSeconds"
            value: "1200"

---

apiVersion: v1
kind: Service
metadata:
  name: web-catalogo
spec:
  selector:
    app: web-catalogo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
  # type: LoadBalancer
