// <auto-generated />
using System;
using LAB.Catalogo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LAB.Catalogo.Migrations
{
    [DbContext(typeof(CatalogoContext))]
    partial class CatalogoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LAB.Catalogo.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96613c80-a99e-4ecb-8504-1a1001e2f86e"),
                            Categoria = "Roupas",
                            Descricao = "Tamanhos Disponíveis: P,M,G,GG",
                            Imagem = "https://img.elo7.com.br/product/original/13EC3B1/camiseta-guns-n-roses-camisetas-personalizadas-de-aniversario.jpg",
                            Nome = "Camiseta Guns n'Roses",
                            Preco = 45.78m
                        },
                        new
                        {
                            Id = new Guid("782ecd42-1a82-44cb-9264-12f881ca31c2"),
                            Categoria = "Roupas",
                            Descricao = "Tamanhos Disponíveis: P,M,G,GG",
                            Imagem = "https://static.stamp.com.br/produto/TS1446_0_TS1446_0.jpeg",
                            Nome = "Camiseta Metálica",
                            Preco = 43.78m
                        },
                        new
                        {
                            Id = new Guid("1ccca33a-28eb-474c-949f-96d7b5a3475b"),
                            Categoria = "Roupas",
                            Descricao = "Tamanhos Disponíveis: P,M,G,GG",
                            Imagem = "https://img.elo7.com.br/product/original/1A8045E/camiseta-bon-jovi-separe-suas-tags-com-virgulas.jpg",
                            Nome = "Camiseta BON JOVI [Feminina]",
                            Preco = 38.23m
                        },
                        new
                        {
                            Id = new Guid("0655cfd4-d2fc-4c8b-bd0d-15afec8f0277"),
                            Categoria = "Roupas",
                            Descricao = "Tamanhos Disponíveis: P,M,G,GG",
                            Imagem = "https://m.media-amazon.com/images/I/6164EADBuNL._AC_SX385_.jpg",
                            Nome = "Camiseta Iron Maden",
                            Preco = 55.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
